version: "3.4"
services:
  explorer:
    build:
      context: .
      args:
        ENVIRONMENT: test
    environment:
      - PROJ_LIB=/usr/share/proj  # This is to fix an odd issue with PyProj
    volumes:
      - ./:/code
      - ./.docker/.datacube_integration.conf:/root/.datacube_integration.conf
    command: flask run --host 0.0.0.0
    ports:
      - "5000:5000"
