version: "3.4"
services:
  explorer:
    build:
      context: .
      dockerfile: Dockerfile.Dev
    volumes:
      - ./.docker/.datacube_integration.conf:/root/.datacube_integration.conf
    ports:
      - 5000:5000
    environment:
      # - DB_HOSTNAME=host.docker.internal
      - DB_HOSTNAME=postgres
      - DB_USERNAME=opendatacube
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=opendatacube
      - DB_PORT=5432
      - FLASK_ENV=development
      - FLASK_APP=cubedash
      - FLASK_DEBUG=1
      # - VIRTUAL_HOST=datacube.explorer
    command: flask run --host 0.0.0.0
    depends_on:
      - postgres

  postgres:
    image: kartoza/postgis:11.0-2.5
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube
    ports:
      - 5432:5432
    restart: always

  # Needed for testing HTTPS
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   container_name: nginx-proxy
  #   ports:
  #     - "5000:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./certs:/etc/nginx/certs
  #   depends_on:
  #     - explorer
