name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - 'develop'

  create:
    tags:
      - v*


env:
  IMAGE_NAME: opendatacube/explorer:latest
  DOCKER_USER: gadockersvc

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Pull docker cache
      run: |
        docker pull ${IMAGE_NAME}:latest         || true

    - name: Build Test Runner Docker
      run: |
        # build and cache first stage (env_builder)
        docker build \
          --target env_builder \
          --cache-from ${IMAGE_NAME}:latest \
          --tag        ${IMAGE_NAME}:build \
          .

    - name: Verify Docker Image
      run: |
        ./check-code.sh --with-docker integration_tests

    - name; Test Security with 
    - name: DockerHub Push
      if: |
        github.event_name == 'push' && (
          github.ref == 'refs/heads/develop'
          )
      run: |
        echo "Login to DockerHub as ${DOCKER_USER}"
        echo "${{ secrets.DockerPassword }}" | docker login -u "${DOCKER_USER}" --password-stdin
        docker push ${IMAGE_NAME}:${BUILDER_TAG}
        docker push ${IMAGE_NAME}:latest
