name: Lint, Test Code and Push Docker image for DEVELOP or TAG

on:
  pull_request:
    paths:
      - '**'

  push:
    paths:
      - '**'

env:
  IMAGE_NAME: opendatacube/explorer

jobs:
  main:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: kartoza/postgis:11.0-2.5
        env:
          POSTGRES_USER: opendatacube
          POSTGRES_PASSWORD: opendatacubepassword
          POSTGRES_DB: opendatacube
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Build Docker
      run: |
        docker build \
          --tag ${IMAGE_NAME}:local \
          --file Dockerfile.Dev \
          .

    - name: Run linting
      run: |
        docker run --rm  \
          -v $(pwd):/code/ \
          -e DB_HOSTNAME=localhost \
          -e DB_USERNAME=opendatacube \
          -e DB_PASSWORD=opendatacubepassword \
          -e DB_DATABASE=opendatacube_test \
          -e DB_PORT=${{ job.services.postgres.ports[5432] }} \
          -e FLASK_ENV=development \
          -e FLASK_APP=cubedash \
          ${IMAGE_NAME}:local \
          make lint

    - name: Run tests
      run: |
        docker run --rm  \
          -v $(pwd):/code/ \
          -v ./.docker/.datacube_integration.conf:/root/.datacube_integration.conf \
          -e DB_HOSTNAME=localhost \
          -e DB_USERNAME=opendatacube \
          -e DB_PASSWORD=opendatacubepassword \
          -e DB_DATABASE=opendatacube \
          -e DB_PORT=${{ job.services.postgres.ports[5432] }} \
          -e FLASK_ENV=development \
          -e FLASK_APP=cubedash \
          ${IMAGE_NAME}:local \
          make lint

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CodeCovToken }}
        # file: ./coverage.xml
        fail_ci_if_error: false

    - name: Pipeline ran
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_CHANNEL: explorer-alerts
        SLACK_ICON_EMOJI: ':github:'
        SLACK_MESSAGE: 'Linting and tests passed! :rocket:'
        SLACK_TITLE: GitHub Action completed
        SLACK_USERNAME: GitHub Actions
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  push:
    runs-on: ubuntu-latest
    needs: main
    if: github.ref == 'refs/heads/develop'

    steps:
    - uses: actions/checkout@v1

    - name: Get the tag
      run: echo ::set-output name=tag::${GITHUB_REF:10}

    - name: tag output
      run: echo ${{ steps.vars.outputs.tag }}

    # - name: tag exists?
    #   if: contains(github.ref, "cubedash-")
    #   run: echo "cubedash- is in the tag"

    - name: Pull docker cache
      run: |
        docker pull ${IMAGE_NAME}:latest || true

    - name: Build and Tag image
      run: |
        docker build \
          --tag ${IMAGE_NAME} \
          --file Dockerfile.Dev \
          .

    - name: Test Security with clair_db
      run: echo "todo"

    - name: DockerHub Push
      run: |
        echo "Login to DockerHub as ${DOCKER_USER}"
        echo "${{ secrets.DockerPassword }}" | docker login -u "${DOCKER_USER}" --password-stdin
        # docker push ${IMAGE_NAME}:${VERSION}
        docker push ${IMAGE_NAME}:latest
